# Generated by Django 5.1.4 on 2024-12-11 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('CityID', models.AutoField(primary_key=True, serialize=False)),
                ('CityName', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('Population', models.IntegerField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('GuideID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('ParticipantID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('TelegramUserID', models.BigIntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('UserID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(blank=True, max_length=100, null=True)),
                ('LastName', models.CharField(blank=True, max_length=100, null=True)),
                ('Username', models.CharField(blank=True, max_length=100, null=True)),
                ('LanguageCode', models.CharField(blank=True, max_length=10, null=True)),
                ('RegistrationDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('LocationID', models.AutoField(primary_key=True, serialize=False)),
                ('LocationName', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=255)),
                ('Description', models.TextField(blank=True, null=True)),
                ('CityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city')),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('QuestID', models.AutoField(primary_key=True, serialize=False)),
                ('QuestName', models.CharField(max_length=200)),
                ('Duration', models.TimeField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Description', models.TextField()),
                ('MaxParticipants', models.IntegerField()),
                ('CityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('QuestionID', models.AutoField(primary_key=True, serialize=False)),
                ('QuestionText', models.TextField()),
                ('QuestionDate', models.DateTimeField(auto_now_add=True)),
                ('IsAnswered', models.BooleanField(default=False)),
                ('ParticipantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('AnswerID', models.AutoField(primary_key=True, serialize=False)),
                ('AnswerText', models.TextField()),
                ('AnswerDate', models.DateTimeField(auto_now_add=True)),
                ('QuestionID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('ReviewID', models.AutoField(primary_key=True, serialize=False)),
                ('Rating', models.IntegerField()),
                ('Comment', models.TextField()),
                ('ReviewDate', models.DateTimeField(auto_now_add=True)),
                ('ParticipantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.participant')),
                ('QuestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.quest')),
            ],
        ),
        migrations.CreateModel(
            name='QuestGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GuideID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.guide')),
                ('QuestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.quest')),
            ],
            options={
                'unique_together': {('QuestID', 'GuideID')},
            },
        ),
        migrations.CreateModel(
            name='QuestLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderNumber', models.IntegerField()),
                ('LocationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
                ('QuestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.quest')),
            ],
            options={
                'unique_together': {('QuestID', 'LocationID')},
            },
        ),
        migrations.CreateModel(
            name='QuestParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegistrationDate', models.DateTimeField(auto_now_add=True)),
                ('ParticipantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.participant')),
                ('QuestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.quest')),
            ],
            options={
                'unique_together': {('QuestID', 'ParticipantID')},
            },
        ),
    ]
